## NOTE:  Do not edit this file.
## Autogenerated by ProjNav (creatfdo.tcl) on Mon Jun 18 14:00:26 Московское время (зима) 2012
##
vlib work
vlog  +acc  "cfi_ctrl_engine_bench.v"
vlog  +acc  "cfi_ctrl_engine.v"
vlog  +acc  "x28fxxxp30.v"
vlog  +acc  "Tools.v"
vlog  +acc  "fifo_w8r32.v"
vlog  +acc  "fifo_w32r8.v"
vlog  +acc  "AddressDriver.v"
vlog  +acc  "Tools.v"
vlog  +acc  "def.h"
vlog  +acc  "data.h"
vlog  +acc  "CUIcommandData.h"
vlog  +acc  "UserData.h"
vlog  +acc  "BankLib.h"
vlog  +acc  "TimingData.h"
vlog  +acc  "C:/Xilinx/14.7/ISE_DS/ISE/verilog/src/glbl.v"
vsim -t 1ps -L xilinxcorelib_ver -L unisims_ver -L unimacro_ver -L secureip -lib work -voptargs=\"+acc\" cfi_ctrl_engine_bench glbl
view wave
add wave sim:/cfi_ctrl_engine_bench/*
add wave sim:/cfi_ctrl_engine_bench/dut/*
add wave sim:/cfi_ctrl_engine_bench/dut/fifo_in/*
add wave sim:/cfi_ctrl_engine_bench/dut/fifo_out/*
view structure
view signals
run 20us
set RunLength 10us 